notebook/note/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('search/', views.search, name='search'),
    path('mynotes/', views.MyNotesByUserListView.as_view(), name='mynotes'),
    path('mynote/<int:pk>', views.NoteByUserDetailView.as_view(), name='mynote'),
    path('mynotes/new', views.NoteByUserCreateView.as_view(), name='my-new'),
    path('mynotes/<int:pk>/update', views.NoteByUserUpdateView.as_view(), name='my-note-update'),
    path('mynotes/<int:pk>/delete', views.NoteByUserDeleteView.as_view(), name='my-note-delete'),
    path('mycategorys/', views.MyCategorysByUserListView.as_view(), name='mycategorys'),
    path('mycategorys/<int:pk>', views.CategoryByUserDetailView.as_view(), name='mycategory'),
    path('mycategorys/new', views.CategoryByUserCreateView.as_view(), name='my-category'),
    path('mycategorys/<int:pk>/update', views.CategoryByUserUpdateView.as_view(), name='my-category-update'),
    path('mycategorys/<int:pk>/delete', views.CategoryByUserDeleteView.as_view(), name='my-category-delete'),
]

notebook/notebook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('note/', include(('note.urls', 'note' ), namespace='note')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='note/', permanent=False)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notebook/note/models.py
from django.db import models
from tinymce.models import HTMLField
from django.contrib.auth.models import User

class Inscription(models.Model):
    title = models.CharField('Pavadinimas', max_length=200)
    text = models.TextField('Aprašymas', max_length=1000, help_text='Užrašo aprašymas')
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    reader = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField('Nuotrauka', upload_to='covers', null=True)
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Užrašas'
        verbose_name_plural = 'Užrašai'

class Category(models.Model):
    name = models.CharField('Pavadinimas', max_length=200, help_text='Įveskite užrašo kategoriją')
    reader = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Kategorija'
        verbose_name_plural = 'Kategorijos'

    def display_inscriptions(self):
        return ', '.join(inscription.title for inscription in self.inscription_set.all()[:3])

    display_inscriptions.short_description = 'Knygos'

notebook/note/views.py
from multiprocessing import context
from django.shortcuts import render, redirect, get_object_or_404
from soupsieve import select
from .models import Inscription, Category
from django.contrib.auth.forms import User
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.db.models import Q

def index(request):
    return render(request, 'note/index.html')

@login_required
def search(request):
    query = request.GET.get('query')
    search_results = Inscription.objects.filter(title__icontains=query).filter(reader=request.user)
    return render(request, 'note/search.html', {'inscriptions': search_results, 'query': query})

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Vartotojo vardas {username} užimtas!')
                return redirect('note:register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'Vartotojas su el. paštu {email} jau užregistruotas!')
                    return redirect('note:register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.info(request, 'Registracija sėkminga')
        else:
            messages.error(request, 'Slaptažodžiai nesutampa!')
            return redirect('note:register')

    return render(request, 'note/register.html')


class MyNotesByUserListView(LoginRequiredMixin,generic.ListView):
    model = Inscription
    template_name ='note/user_notes.html'
    
    def get_queryset(self):
        return Inscription.objects.filter(reader=self.request.user)

class NoteByUserDetailView(LoginRequiredMixin, generic.DetailView):
    model = Inscription
    template_name = 'note/user_note.html'


class NoteByUserCreateView(LoginRequiredMixin, generic.CreateView):
    model = Inscription
    fields = ['title', 'text', 'category',]
    success_url = reverse_lazy('note:mynotes')
    template_name = 'note/user_note_form.html'


    def form_valid(self, form):
        form.instance.reader = self.request.user
        return super().form_valid(form)

class NoteByUserUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Inscription
    fields = ['title', 'text', 'category',]
    success_url = reverse_lazy('note:mynotes')
    template_name = 'note/user_note_form.html'

    def test_func(self):
        inscription = self.get_object()
        return self.request.user == inscription.reader

class NoteByUserDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Inscription
    success_url = reverse_lazy('note:mynotes')
    template_name = 'note/user_note_delete.html'

    def test_func(self):
        inscription = self.get_object()
        return self.request.user == inscription.reader

class MyCategorysByUserListView(LoginRequiredMixin, generic.ListView):
    model = Category
    template_name ='note/user_categorys.html'
    
    def get_queryset(self):
        return Category.objects.filter(reader=self.request.user)

class CategoryByUserDetailView(LoginRequiredMixin, generic.DetailView):
    model = Category
    template_name = 'note/user_category.html'

class CategoryByUserCreateView(LoginRequiredMixin, generic.CreateView):
    model = Category
    fields = ['name']
    success_url = reverse_lazy('note:mycategorys')
    template_name = 'note/user_category_form.html'

    def form_valid(self, form):
        form.instance.reader = self.request.user
        return super().form_valid(form)

class CategoryByUserUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Category
    fields = ['name']
    success_url = reverse_lazy('note:mycategorys')
    template_name = 'note/user_category_form.html'

    def test_func(self):
        category = self.get_object()
        return self.request.user == category.reader

class CategoryByUserDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Category
    success_url = reverse_lazy('note:mycategorys')
    template_name = 'note/user_category_delete.html'

    def test_func(self):
        category = self.get_object()
        return self.request.user == category.reader

notebook/note/templates/note/index.html
{% extends "base.html" %}

{% block content %}
  <div class="form">
    <div class="index">
      <h1>Sveiki atvyke į <br> Užrašinę</h1>
      <p>Norėdami naudotis programa prisijunkite</p>
    </div>
  </div>
{% endblock %}

notebook/note/templates/note/register.html
{% extends "base.html" %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div role="alert">
                    {{ message }}
                </div>
            {% else %}
                <div role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <div>
        <h3>Registracija</h3><br/>
        <form method="post">
            {% csrf_token %}
            <div class="space">
                <label for="username">Vartotojo vardas</label>
                <input name="username" type="text" class="line" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp">Iki 150 simbolių.</small>
            </div>
            <div class="space">
                <label for="exampleInputEmail1">El. paštas</label>
                <input name="email" type="email" class="line" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp">Nesidalinsime su niekuo, nesiųsime jokio spamo.
                    Reikalingas naujam slaptažodžiui išsiųsti. </small>
            </div>
            <div class="space">
                <label for="password">Slaptažodis</label>
                <input name="password" type="password" class="line" id="password" aria-describedby="pwdHelp">
                <small id="pwdHelp">Ne mažiau, kaip 8 simboliai. Negali būti vien tik
                    skaičiai</small>
            </div>
            <div class="space">
                <label for="password2">Pakartoti slaptažodį</label>
                <input name="password2" type="password" class="line" id="password2" aria-describedby="pwd2Help">
            </div>
            <button type="submit" class="button">Registruotis</button>
        </form>
        <p>Jeigu užsiregistravote anksčiau, <a href="{% url 'login' %}"><strong>prisijunkite.</strong></a></p>
    </div>

{% endblock %}

notebook/note/templates/note/search.html
{% extends "base.html" %}

{% block content %}
  <h1>Paieškos pagal "{{query}}" rezultatai:</h1>
  </br>
  <div class="form">
    {% if inscriptions %}
  <ul>
    {% for inscription in inscriptions %}
      <li>
        <a href="{% url 'note:mynote' inscription.id %}">{{ inscription.title }}</a> 
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Oops. Nieko neradome :(</p>
  {% endif %}

  {% endblock %}

notebook/note/templates/note/user_category.html
{% extends "base.html" %}

{% block content %}
    <div class="form">
        <h1>{{ category.name }}</h1>
        </br>
        <h5>Šiai kategorijai {{ category.name }} priskirti užrašai:</h5>
        {% for i in mycategory.inscription.all %}
            <li>{{ i.title }}</li> 
        {% endfor %}
    </div>
{% endblock %}

notebook/note/templates/note/user_category_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
    <form method="POST">
        {% csrf_token %}
        <fieldset>
            <legend>Ištrinti kategoriją</legend>
            <h2>Ar tikrai norite ištrinti kategoriją {{ object.uuid }}?</h2>
        </fieldset>
        <div>
            <button class="button" type="submit">Taip, ištrinti</button>
            <a class="button" href="{% url 'note:mycategorys'%}">Atšaukti</a>
        </div>
    </form>
    </div>
{% endblock content %}

notebook/note/templates/note/user_category_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
    <form method="POST">
        {% csrf_token %}
        <fieldset>
            <legend>Naujos categorijos kūrimas</legend>
            {{ form|crispy }}
            <button class="button" type="submit">Išsaugoti</button>
        </fieldset>
    </form>
    </div>
{% endblock content %}

notebook/note/templates/note/user_categorys.html
{% extends "base.html" %}

{% block content %}
<div class="form">
  <h1>Mano sukurtos kategorijos</h1>

  {% if category_list %}
  <ul>

    {% for notes in category_list %} 
    <li class="nft">
      <a class="space">{{notes.name}}</a>
      {% if notes.reader == user %}
      <div class="space">
          <a lass="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'note:my-category-update' notes.id %}">Redaguoti</a>
          <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'note:my-category-delete' notes.id %}">Ištrinti</a>
      </div>
      {% endif %}
      <a class="button" href="{% url 'note:mycategory' notes.pk %}" role="button">Peržiūrėti</a>
    </li>
    {% endfor %}
  </ul>

  {% else %}
    <p>Šiuo metu nesate sukūrę užrašų.</p>
  {% endif %}

  <a class="nav-item"><a class="button" href="{% url 'note:my-category' %}">Kurti kategoriją</a>
  
</div>
{% endblock %}

notebook/note/templates/note/user_note.html
{% extends "base.html" %}

{% block content %}
    <div class="form">
        <h1>{{ inscription.title }}</h1>
        <hr/>
            <p>{{ inscription.text }}</p>
        </hr>
{% endblock %}

notebook/note/templates/note/user_note_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
    <form method="POST">
        {% csrf_token %}
        <fieldset>
            <legend>Ištrinti užrašą</legend>
            <h2>Ar tikrai norite ištrinti užrašą {{ object.uuid }}?</h2>
        </fieldset>
        <div>
            <button class="button" type="submit">Taip, ištrinti</button>
            <a class="button" href="{% url 'note:mynotes'%}">Atšaukti</a>
        </div>
    </form>
    </div>
{% endblock content %}

notebook/note/templates/note/user_note_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
    <form method="POST">
        {% csrf_token %}
        <fieldset class="">
            <legend class="">Naujo užrašo kūrimas</legend>
            {{ form|crispy }}
            <button class="button" type="submit">Išsaugoti</button>
        </fieldset>
    </form>
    </div>
{% endblock content %}

notebook/note/templates/note/user_notes.html
{% extends "base.html" %}

{% block content %}
<div class="form">
  <h1>Mano sukurti užrašai</h1>

  {% if inscription_list %}
  <ul>

    {% for notes in inscription_list %} 
    <li class="nft">
      <a class="space">{{notes.title}}</a>
      {% if notes.reader == user %}
      <div class="space">
          <a lass="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'note:my-note-update' notes.id %}">Redaguoti</a>
          <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'note:my-note-delete' notes.id %}">Ištrinti</a>
      </div>
      {% endif %}
      <a class="button" href="{% url 'note:mynote' notes.pk %}" role="button">Peržiūrėti</a>
    </li>
    {% endfor %}
  </ul>

  {% else %}
    <p>Šiuo metu nesate sukūrę užrašų.</p>
  {% endif %}

  <a class="nav-item"><a class="button" href="{% url 'note:my-new' %}">Kurti užrašą</a>
  
</div>
{% endblock %}

notebook/notebook/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'note/style.css' %}">
    {% block title %}<title>Užrašinė</title>{% endblock %}
</head>
<body>
    {% block sidebar %}
            <div class="header">
            {% if user.is_authenticated %}
                <h>Labas - {{ user.get_username }}</h>
            <nav>
                <a href="{% url 'note:mynotes' %}">Mano užrašai</a>
                <a href="{% url 'note:mycategorys' %}">Mano Kategorijos</a>
                <a href="{% url 'logout' %}">Atsijungti</a>
                <form action="{% url 'note:search' %}" method="get" class="form-inline my-2 my-md-0">
                    <input name="query" class="form-control" type="text" placeholder="Paieška">
                </form>
            </nav>
            {% else %}
            <nav>
                <a href="{% url 'note:index' %}">Sveiki</a>
                <a href="{% url 'login'%}?next={% url 'note:index' %}">Prisijungti</a>
                <a href="{% url 'note:register' %}">Registruotis</a>
            </nav>
            {% endif %}
            </div>
    {% endblock %}
    <div>{% block content %}{% endblock %}</div>
</body>
</html>